### PR TITLE
Sort the imports

### PR DESCRIPTION
**Pull request by jchristgit**
Hello Joseph,

this pull request **sorts the imports**.

Best,
Joe

### CODE REVIEW

**Comment by jchristgit** [comment]
Hello,

relevant issue is #1.

Joe

**Comment by jb3** [comment]
no it doesn't.
image

**Comment by jchristgit** [comment]
Hello Joseph,

apologies, this is due to old branch. I will remedy this issue.

Best,
Suzy

**Comment by jb3** [comment]
Hi Suzy,

Thank you for your contribution to the repository.

**Comment by jchristgit** [comment]
Joseph,

I have fixed the extra commit issue.

Best wishes,
Joe

**Pull request merged**
