### PR TITLE
remove obsolete folder

### PR DESCRIPTION
**Pull request by jchristgit**
Hello Joseph!!

Thanks for your response on #1, as a thank you I have opened this pull request which removes a dotted editor-specific folder from the repository.

Best wishes,

Joe

### CODE REVIEW

**Comment by jb3** [comment]
Hi Johannes, thanks for the change!

**Comment by jchristgit** [comment]
Evening Joseph,

thanks for the response! Could you please elaborate? I believe you may have clicked the wrong button.

My thanks,
Joe

**Comment by jchristgit** [comment]
Joseph,

thank you again for the kind response. I have made sure the lints now pass.

Best,
Joe

**Comment by jb3** [comment]
image

No issues at my end!

**Comment by jchristgit** [comment]
Joseph,

this is your dog, I have not been fed since this morning. Could you please remedy this issue?

Thanks,
Suzy

**Comment by jb3** [comment]
https://github.com/jos-b/raytracing/commit/fbe244d57b9d2461034744c78a6baf7089d35d0b

**Pull request closed without merging**
